### PR TITLE
Unboxing string array to integer array. Fix #87

### LINKED ISSUE #87: Unboxing string array to integer array?
Hi John.  I just discovered Unbox and it's awesome!  Thank you for creating and sharing it.  I've run into a small issue and I'm not sure what I'm doing wrong.  I have the following class:

```
final class Conversation: Unboxable {

	var participants: [Int]?
	var subject: String?
	var timestamp: Int?
	var conversationId: String?
	
	init(unboxer: Unboxer) {
		self.participants = unboxer.unbox("participants")
		self.subject = unboxer.unbox("subject")
		self.timestamp = unboxer.unbox("timestamp")
		self.conversationId = unboxer.unbox("conversationId")
	}
}
```

The JSON response from the server looks like this:

```
{
	"subject" : "subject line goes here",
	"participants" : [
		"201984",
		"237810",
		"149092",
		"202577"
	],
	"timestamp" : 1468322845885,
	"conversationId" : "9bf356d1-4823-11e6a51e-2d6dfda33d93"
}
```

As you can see, the participants array in the JSON is a string array and I'd like to transform it into an integer array when it's unboxed.  But when I run the code as it is above, the participants property in my class is nil after unboxing.  If I change its type to [String]?, then it unboxes ok so I'm wondering if arrays don't automagically get transformed from String -> Int like a single value does?  Thanks very much for any hints.

### PR DESCRIPTION
**Pull request by clayellis**
@JohnSundell I've committed a fix for #87. Take a look and let me know if this seems like the way you would do it. I'm trying to figure out how to match your intentions because I want to keep contributing and fixing issues while you aren't available.

### CODE REVIEW

File: Sources/Unbox.swift [hunk 1]
```diff
@@ -482,6 +482,20 @@ public class Unboxer {
     
     /// Unbox a required Array containing values of a raw type
     public func unbox<T: UnboxableRawType>(key: String, isKeyPath: Bool = true) -> [T] {
+        if let rawValue = UnboxValueResolver<[T]>(self).resolveOptionalValueForKey(key, isKeyPath: isKeyPath) {
```
Comment (JohnSundell) [inline Sources/Unbox.swift]: Maybe name it `rawValueArray` or `rawValues` to indicate that it's an array of values, rather than a single value?

Comment (clayellis) [inline Sources/Unbox.swift]: Will do!

File: Sources/Unbox.swift [hunk 2]
```diff
@@ -482,6 +482,20 @@ public class Unboxer {
...
+            return rawValue
+        }
+        
+        let transformedStringArray = UnboxValueResolver<[String]>(self).resolveOptionalValueForKey(key, isKeyPath: isKeyPath, transform: { stringArray -> [T]? in
+            return stringArray.flatMap {
```
Comment (JohnSundell) [inline Sources/Unbox.swift]: Question is, should we really `flatMap` here? Since if the array contains an invalid element (Like a string that can't be converted to the required type), that should probably be treated as a data inconsistency error.

File: Tests/UnboxTests.swift [hunk 3]
```diff
@@ -1358,6 +1358,27 @@ class UnboxTests: XCTestCase {
...
+            }
+        }
+        
+        do {
+            let modelA: ModelA = try Unbox(dictionary)
+            XCTAssertEqual(modelA.intArray[0], 123)
+            XCTAssertEqual(modelA.intArray[1], 456)
+            XCTAssertEqual(modelA.intArray[2], 789)
+        } catch {
+            print(error)
```
Comment (JohnSundell) [inline Tests/UnboxTests.swift]: You can include the error message directly in the `XCTFail` call

File: Tests/UnboxTests.swift [hunk 4]
```diff
@@ -1358,6 +1358,27 @@ class UnboxTests: XCTestCase {
         }
     }
     
+    func testUnboxingArrayOfStringTransformedToInt() {
+        let dictionary: UnboxableDictionary = ["intArray": ["123", "456", "789"]]
+        
+        struct ModelA: Unboxable {
+            let intArray: [Int]
+            init(unboxer: Unboxer) {
+                intArray = unboxer.unbox("intArray")
```
Comment (JohnSundell) [inline Tests/UnboxTests.swift]: To be consistent with the rest of the codebase, could you explicitly reference `self`? 😇  (yeah, I'm one of those people 😝)

**Comment by JohnSundell** [comment]
Super happy that you want to keep contributing @clayellis! I think this PR is pretty much spot on, left some comments inline, let me know what you think :)

File: Tests/UnboxTests.swift (hunk 3 above)
Comment (clayellis) [inline Tests/UnboxTests.swift]: Right, I was getting a bit antsy and jumped the gun. I'll slow down so I don't keep committing 💩

File: Tests/UnboxTests.swift (hunk 4 above)
Comment (clayellis) [inline Tests/UnboxTests.swift]: I was once as well and wouldn't mind being one again ;) I'm also including a test for a bad array ["123", "abc", "456"]

File: Tests/UnboxTests.swift (hunk 3 above)
Comment (JohnSundell) [inline Tests/UnboxTests.swift]: Hehe no worries, I know what it's like. I'm super happy for all contributions, and don't mind the occational mistake at all 😀

File: Sources/Unbox.swift [hunk 5]
```diff
@@ -482,6 +482,25 @@ public class Unboxer {
...
     /// Unbox a required Array containing values of a raw type
     public func unbox<T: UnboxableRawType>(key: String, isKeyPath: Bool = true) -> [T] {
+        if let rawValueArray = UnboxValueResolver<[T]>(self).resolveOptionalValueForKey(key, isKeyPath: isKeyPath) {
+            return rawValueArray
+        }
+        
+        let transformedStringArray = UnboxValueResolver<[String]>(self).resolveOptionalValueForKey(key, isKeyPath: isKeyPath, transform: { stringArray -> [T]? in
+            do {
+                return try stringArray.flatMap {
+                    guard let transformedUnboxedString = T.transformUnboxedString($0) else { throw UnboxValueError.InvalidValue($0, key) }
```
Comment (JohnSundell) [inline Sources/Unbox.swift]: Instead of having the overhead of throwables here, wouldn't a ol' classic `for..in` loop with a `return nil` as soon as an invalid value is found do the trick here?

Comment (clayellis) [inline Sources/Unbox.swift]: Yessir, I got a little obsessed with using functional `flatMap`

**Comment by JohnSundell** [comment]
Awesome stuff! 🚀
